import { VideoCategory } from "./interfaces";
import {
    Movie,
    DriveEta,
    MusicNote,
    Pets,
    SportsSoccer,
    FlightTakeoff,
    SportsEsports,
    People,
    EmojiEmotions,
    Announcement,
    CastForEducation,
    WbIncandescent,
    MoneyOff,
    Description,
    DirectionsBike,
} from "@material-ui/icons";

const categoryList: VideoCategory[] = [
    { id: "1", name: "Film & Animation", icon: Movie },
    { id: "2", name: "Autos & Vehicles", icon: DriveEta },
    { id: "10", name: "Music", icon: MusicNote },
    { id: "15", name: "Pets & Animals", icon: Pets },
    { id: "17", name: "Sports", icon: SportsSoccer },
    { id: "18", name: "Short Movies", icon: Movie },
    { id: "19", name: "Travel & Events", icon: FlightTakeoff },
    { id: "20", name: "Gaming", icon: SportsEsports },
    { id: "21", name: "VideoBlogging", icon: Movie },
    { id: "22", name: "People & Blogs", icon: People },
    { id: "23", name: "Comedy", icon: EmojiEmotions },
    { id: "24", name: "Entertainment", icon: People },
    { id: "25", name: "News & Politics", icon: Announcement },
    { id: "26", name: "Howto & Style", icon: People },
    { id: "27", name: "Education", icon: CastForEducation },
    { id: "28", name: "Science & Technology", icon: WbIncandescent },
    { id: "29", name: "Nonprofits & Activism", icon: MoneyOff },
    { id: "30", name: "Movies", icon: Movie },
    { id: "31", name: "Anime/Animation", icon: Movie },
    { id: "32", name: "Action/Adventure", icon: DirectionsBike },
    { id: "33", name: "Classics", icon: MusicNote },
    { id: "34", name: "Comedy", icon: EmojiEmotions },
    { id: "35", name: "Documentary", icon: Description },
    { id: "36", name: "Drama", icon: Movie },
    { id: "37", name: "Family", icon: People },
    { id: "38", name: "Foreign", icon: People },
    { id: "39", name: "Horror", icon: Movie },
    { id: "40", name: "Sci-Fi/Fantasy", icon: Movie },
    { id: "41", name: "Thriller", icon: Movie },
    { id: "42", name: "Shorts", icon: Movie },
    { id: "43", name: "Shows", icon: Movie },
    { id: "44", name: "Trailers", icon: Movie },
];

export default categoryList;
