import { categoryItem } from "./interfaces";

export const categoryList: string[] = [
    "",
    "Film & Animation",
    "Autos & Vehicles",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Music",
    "",
    "",
    "",
    "",
    "Pets & Animals",
    "",
    "Sports",
    "Short Movies",
    "Travel & Events",
    "Gaming",
    "Videoblogging",
    "People & Blogs",
    "Comedy",
    "Entertainment",
    "News & Politics",
    "Howto & Style",
    "Education",
    "Science & Technology",
    "Nonprofits & Activism",
    "Movies",
    "Anime/Animation",
    "Action/Adventure",
    "Classics",
    "Comedy",
    "Documentary",
    "Drama",
    "Family",
    "Foreign",
    "Horror",
    "Sci-Fi/Fantasy",
    "Thriller",
    "Shorts",
    "Shows",
    "Trailers",
];

export const categoryListIndex: number[] = [
    1,
    2,
    10,
    15,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
];

export const categoryItems: categoryItem[] = [
    { id: "1", name: "Film & Animation" },
    { id: "2", name: "Autos & Vehicles" },
    { id: "10", name: "Music" },
    { id: "15", name: "Pets & Animals" },
    { id: "17", name: "Sports" },
    { id: "18", name: "Short Movies" },
    { id: "19", name: "Travel & Events" },
    { id: "20", name: "Gaming" },
    { id: "21", name: "VideoBlogging" },
    { id: "22", name: "People & Blogs" },
    { id: "23", name: "Comedy" },
    { id: "24", name: "Entertainment" },
    { id: "25", name: "News & Politics" },
    { id: "26", name: "Howto & Style" },
    { id: "27", name: "Education" },
    { id: "28", name: "Science & Technology" },
    { id: "29", name: "Nonprofits & Activism" },
    { id: "30", name: "Movies" },
    { id: "31", name: "Anime/Animation" },
    { id: "32", name: "Action/Adventure" },
    { id: "33", name: "Classics" },
    { id: "34", name: "Comedy" },
    { id: "35", name: "Documentary" },
    { id: "36", name: "Drama" },
    { id: "37", name: "Family" },
    { id: "38", name: "Foreign" },
    { id: "39", name: "Horror" },
    { id: "40", name: "Sci-Fi/Fantasy" },
    { id: "41", name: "Thriller" },
    { id: "42", name: "Shorts" },
    { id: "43", name: "Shows" },
    { id: "44", name: "Trailers" },
];
